### ISSUE TITLE
gifsicle@0.1.7 causing issues when running npm install

### ISSUE THREAD

**Issue by jamesaps** [timsim00/node-sdk-backbone-app#5]
```
^Cjames@JamesPlayground:~/node-sdk-backbone-app$ npm install
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated coffee-script@1.7.1: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated coffee-script@1.3.3: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue            t" (no hyphen)
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated coffee-script@1.6.3: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)                    st version of pug instead of jade
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated connect@2.8.8: connect 2.x series is deprecated                                                     ty with current and future versions of Node.js
npm WARN deprecated express3-handlebars@0.5.2: THIS PACKAGE HAS BEEN RENAMED TO: express-handlebars
npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@0.4.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue             id a RegExp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130   id a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated find-file@0.1.4: Use the globby package instead
npm WARN deprecated hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer
                                                                                                                        bone-app/node_modules/gifsicle/cli.js
> ws@0.4.32 install /home/james/node-sdk-backbone-app/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/home/james/node-sdk-backbone-app/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
bufferutil.target.mk:103: recipe for target 'Release/obj.target/bufferutil/src/bufferutil.o' failed
make: Leaving directory '/home/james/node-sdk-backbone-app/node_modules/ws/build'

> phantomjs@1.9.20 install /home/james/node-sdk-backbone-app/node_modules/phantomjs
> node install.js

PhantomJS not found on PATH
Download already available at /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
Verified checksum of previously downloaded file
Extracting tar contents (via spawned process)
Removing /home/james/node-sdk-backbone-app/node_modules/phantomjs/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2-extract-1537442479348/phantomjs-1.9.8-linux-x86_64 -> /home/james/node-sdk-backbone-app/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /home/james/node-sdk-backbone-app/node_modules/phantomjs/lib/phantom/bin/phantomjs

> gifsicle@0.1.7 postinstall /home/james/node-sdk-backbone-app/node_modules/gifsicle
> node index.js

path.js:39
    throw new ERR_INVALID_ARG_TYPE('path', 'string', path);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at assertPath (path.js:39:11)
    at Object.basename (path.js:1299:5)
    at /home/james/node-sdk-backbone-app/node_modules/download/index.js:35:43
    at each (/home/james/node-sdk-backbone-app/node_modules/each-async/each-async.js:63:4)
    at module.exports (/home/james/node-sdk-backbone-app/node_modules/download/index.js:33:5)
    at /home/james/node-sdk-backbone-app/node_modules/bin-wrapper/index.js:108:20
    at /home/james/node-sdk-backbone-app/node_modules/bin-wrapper/index.js:141:24
    at /home/james/node-sdk-backbone-app/node_modules/bin-check/index.js:30:20
    at /home/james/node-sdk-backbone-app/node_modules/executable/index.js:39:20
    at FSReqWrap.oncomplete (fs.js:152:21)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@github:pipobscure/fsevents#7dcdf9fa3f8956610fd6f69f72c67bace2de7138 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@0.2.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN grunt-util-args@0.0.6 requires a peer of grunt@~1 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gifsicle@0.1.7 postinstall: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gifsicle@0.1.7 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/james/.npm/_logs/2018-09-20T11_21_22_198Z-debug.log
```

**Comment by npgoossen** [comment]
Saw this same error, and it's an issue with an out of date package pulling in gifsicle@0.1.7 which given your node version is incompatible. For this project I found grunt-contrib-imagemin was out of date and pulling in gifsicle. Updating grunt-contrib-imagemin to 4.0.0 (the latest currently) in the package.json file fixed the issue!
